spring:
  application:
    name: member

---
spring:
  profiles: local

server:
  port: 8763

message:
   cacheSecond: 60

aws:
   credential:
      accessKey: AKIASY4N752BIFONDGOR
      secretKey: 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 
   endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
   region: ap-northeast-2
   dynamodb:
      memberTbl: local_member
      memberPartition: memberBase

eureka:
  instance:
    prefer-ip-address: true # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 여부
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# hystrix dashboard 설정      
management:
   endpoints:
      web:
         exposure:
            include: "*"
---
spring:
  profiles: dev
  application:
    name: member

server:
  port: 8764

message:
   cacheSecond: 60

aws:
   credential:
      accessKey: AKIASY4N752BIFONDGOR
      secretKey: 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 
   endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
   region: ap-northeast-2
   dynamodb:
      memberTbl: local_member
      memberPartition: memberBase

eureka:
  instance:
    prefer-ip-address: true # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 여부
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# hystrix dashboard 설정      
management:
   endpoints:
      web:
         exposure:
            include: "*"
  
---
spring:
  profiles: prd

server:
  port: 8763

aws:
  ec2:
    serviceIp:
      first: 999.99.99
      second: 888.88.88
      
# 유레카 서버 이중화 방안 생각
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${aws.ec2.serviceIp.first}:8761/eureka/, http://${aws.ec2.serviceIp.second}:8761/eureka/